//! minifb Key -> PS/2 set-1 扫描码 (bit9=0x100 表示 E0 扩展键)

use minifb::Key;

/// 返回 (Key, scancode) 表
pub fn table() -> &'static [(Key, u32)] {
    const E: u32 = 0x100;
    const T: &[(Key, u32)] = &[
        // 字母
        (Key::A, 0x1E),
        (Key::B, 0x30),
        (Key::C, 0x2E),
        (Key::D, 0x20),
        (Key::E, 0x12),
        (Key::F, 0x21),
        (Key::G, 0x22),
        (Key::H, 0x23),
        (Key::I, 0x17),
        (Key::J, 0x24),
        (Key::K, 0x25),
        (Key::L, 0x26),
        (Key::M, 0x32),
        (Key::N, 0x31),
        (Key::O, 0x18),
        (Key::P, 0x19),
        (Key::Q, 0x10),
        (Key::R, 0x13),
        (Key::S, 0x1F),
        (Key::T, 0x14),
        (Key::U, 0x16),
        (Key::V, 0x2F),
        (Key::W, 0x11),
        (Key::X, 0x2D),
        (Key::Y, 0x15),
        (Key::Z, 0x2C),
        // 数字行
        (Key::Key1, 0x02),
        (Key::Key2, 0x03),
        (Key::Key3, 0x04),
        (Key::Key4, 0x05),
        (Key::Key5, 0x06),
        (Key::Key6, 0x07),
        (Key::Key7, 0x08),
        (Key::Key8, 0x09),
        (Key::Key9, 0x0A),
        (Key::Key0, 0x0B),
        // 功能键
        (Key::F1, 0x3B),
        (Key::F2, 0x3C),
        (Key::F3, 0x3D),
        (Key::F4, 0x3E),
        (Key::F5, 0x3F),
        (Key::F6, 0x40),
        (Key::F7, 0x41),
        (Key::F8, 0x42),
        (Key::F9, 0x43),
        (Key::F10, 0x44),
        (Key::F11, 0x57),
        (Key::F12, 0x58),
        // 控制键
        (Key::Backspace, 0x0E),
        (Key::Tab, 0x0F),
        (Key::Enter, 0x1C),
        (Key::Escape, 0x01),
        (Key::Space, 0x39),
        (Key::CapsLock, 0x3A),
        (Key::NumLock, 0x45),
        (Key::ScrollLock, 0x46),
        // 符号
        (Key::Minus, 0x0C),
        (Key::Equal, 0x0D),
        (Key::LeftBracket, 0x1A),
        (Key::RightBracket, 0x1B),
        (Key::Backslash, 0x2B),
        (Key::Semicolon, 0x27),
        (Key::Apostrophe, 0x28),
        (Key::Backquote, 0x29),
        (Key::Comma, 0x33),
        (Key::Period, 0x34),
        (Key::Slash, 0x35),
        // 方向/编辑 (E0)
        (Key::Up, E | 0x48),
        (Key::Down, E | 0x50),
        (Key::Left, E | 0x4B),
        (Key::Right, E | 0x4D),
        (Key::Insert, E | 0x52),
        (Key::Delete, E | 0x53),
        (Key::Home, E | 0x47),
        (Key::End, E | 0x4F),
        (Key::PageUp, E | 0x49),
        (Key::PageDown, E | 0x51),
        // 修饰键
        (Key::LeftShift, 0x2A),
        (Key::RightShift, 0x36),
        (Key::LeftCtrl, 0x1D),
        (Key::RightCtrl, E | 0x1D),
        (Key::LeftAlt, 0x38),
        (Key::RightAlt, E | 0x38),
        (Key::LeftSuper, E | 0x5B),
        (Key::RightSuper, E | 0x5C),
        (Key::Menu, E | 0x5D),
        // 小键盘
        (Key::NumPad0, 0x52),
        (Key::NumPad1, 0x4F),
        (Key::NumPad2, 0x50),
        (Key::NumPad3, 0x51),
        (Key::NumPad4, 0x4B),
        (Key::NumPad5, 0x4C),
        (Key::NumPad6, 0x4D),
        (Key::NumPad7, 0x47),
        (Key::NumPad8, 0x48),
        (Key::NumPad9, 0x49),
        (Key::NumPadDot, 0x53),
        (Key::NumPadSlash, E | 0x35),
        (Key::NumPadAsterisk, 0x37),
        (Key::NumPadMinus, 0x4A),
        (Key::NumPadPlus, 0x4E),
        (Key::NumPadEnter, E | 0x1C),
    ];
    T
}
